<?xml version="1.0" encoding="utf-8"?><Database Name="DrinkzApp" Class="DrinkzAppBDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-L7A4397;Initial Catalog=DrinkzApp;Integrated Security=True" SettingsObjectName="DrinkzApp.Data.Properties.Settings" SettingsPropertyName="DrinkzAppConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="PK_ADDRESS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ZIP_CODE" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="STREET" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="STATE" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="FK_PROFILE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Profile_Address" Member="Profile" ThisKey="FK_PROFILE" OtherKey="PK_PROFILE" Type="Profile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="PK_CATEGORY" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="UF" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="REGION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Category_Drink" Member="Drinks" ThisKey="PK_CATEGORY" OtherKey="FK_CATEGORY" Type="Drink" />
    </Type>
  </Table>
  <Table Name="dbo.Ingredients" Member="Ingredients">
    <Type Name="Ingredient">
      <Column Name="PK_INGREDIENTS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QTD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FK_DRINK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Drink_Ingredient" Member="Drink" ThisKey="FK_DRINK" OtherKey="PK_DRINK" Type="Drink" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Likes" Member="Likes">
    <Type Name="Like">
      <Column Name="PK_LIKE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_DRINK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_PROFILE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Profile_Like" Member="Profile" ThisKey="FK_PROFILE" OtherKey="PK_PROFILE" Type="Profile" IsForeignKey="true" />
      <Association Name="Drink_Like" Member="Drink" ThisKey="FK_DRINK" OtherKey="PK_DRINK" Type="Drink" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Picture" Member="Pictures">
    <Type Name="Picture">
      <Column Name="PK_PICTURE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="URL_IMAGE" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FK_DRINK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Drink_Picture" Member="Drink" ThisKey="FK_DRINK" OtherKey="PK_DRINK" Type="Drink" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Preferences" Member="Preferences">
    <Type Name="Preference">
      <Column Name="PK_PREFERENCES" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_DRINK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_PROFILE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Profile_Preference" Member="Profile" ThisKey="FK_PROFILE" OtherKey="PK_PROFILE" Type="Profile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Profile" Member="Profiles">
    <Type Name="Profile">
      <Column Name="PK_PROFILE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FACEBOOK_ID" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="URL_IMAGE" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DEVICE_ID" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="OS_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Profile_Address" Member="Addresses" ThisKey="PK_PROFILE" OtherKey="FK_PROFILE" Type="Address" />
      <Association Name="Profile_Like" Member="Likes" ThisKey="PK_PROFILE" OtherKey="FK_PROFILE" Type="Like" />
      <Association Name="Profile_Preference" Member="Preferences" ThisKey="PK_PROFILE" OtherKey="FK_PROFILE" Type="Preference" />
      <Association Name="Profile_Share" Member="Shares" ThisKey="PK_PROFILE" OtherKey="FK_PROFILE" Type="Share" />
      <Association Name="Profile_Drink" Member="Drinks" ThisKey="PK_PROFILE" OtherKey="PK_PROFILE" Type="Drink" />
    </Type>
  </Table>
  <Table Name="dbo.Shares" Member="Shares">
    <Type Name="Share">
      <Column Name="PK_SHARE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_DRINK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_PROFILE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Profile_Share" Member="Profile" ThisKey="FK_PROFILE" OtherKey="PK_PROFILE" Type="Profile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Drink" Member="Drinks">
    <Type Name="Drink">
      <Column Name="PK_DRINK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="HOWTO" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="LIKES" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_CATEGORY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VIEWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATION_DATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PK_PROFILE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YOUTUBE_URL" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Drink_Ingredient" Member="Ingredients" ThisKey="PK_DRINK" OtherKey="FK_DRINK" Type="Ingredient" />
      <Association Name="Drink_Like" Member="Likes1" ThisKey="PK_DRINK" OtherKey="FK_DRINK" Type="Like" />
      <Association Name="Drink_Picture" Member="Pictures" ThisKey="PK_DRINK" OtherKey="FK_DRINK" Type="Picture" />
      <Association Name="Category_Drink" Member="Category" ThisKey="FK_CATEGORY" OtherKey="PK_CATEGORY" Type="Category" IsForeignKey="true" />
      <Association Name="Profile_Drink" Member="Profile" ThisKey="PK_PROFILE" OtherKey="PK_PROFILE" Type="Profile" IsForeignKey="true" />
    </Type>
  </Table>
</Database>